// Run against a fresh, isolated database at localhost:8765. Requires Playwright.
const {chromium}=require('playwright');
(async()=>{
for(let i=0;i<50;i++){try{await fetch('http://127.0.0.1:8765/health');break}catch{await new Promise(r=>setTimeout(r,100))}}const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/app/api/coach')&&r.status()>=400)errors.push(r.status()+' '+r.url())});await page.goto('http://127.0.0.1:8765/app');await page.waitForTimeout(600);
await page.locator('[data-tab="athlete"]').click();await page.locator('#ap_age').fill('33');await page.locator('#ap_running_years').fill('3');await page.locator('#ap_recent_weekly_km').fill('50');await page.locator('#ap_threshold_pace').fill('300');await page.locator('#ap_threshold_hr').fill('167');await page.locator('#ap_max_hr').fill('183');await page.locator('#ap_max_session_minutes').fill('120');for(const c of await page.locator('[name="availableDay"]').all())await c.check();await page.locator('#athleteForm button').click();await page.waitForFunction(()=>document.getElementById('athleteStatus').textContent.includes('saved'));
const today=await page.locator('#coachStart').inputValue();const end=new Date(today+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+90);
await page.locator('[data-tab="plan"]').click();await page.locator('#raceName').fill('Test race');await page.locator('#raceDate').fill(end.toISOString().slice(0,10));await page.locator('#raceDistance').fill('21.0975');await page.locator('#raceTime').fill('01:55');await page.locator('#goalForm button').click();await page.waitForFunction(()=>document.getElementById('goalStatus').textContent.includes('saved'));
await page.locator('[data-tab="coach"]').click();await page.locator('#coachGenerate').click();await page.waitForFunction(()=>document.getElementById('coachStatus').textContent.includes('sessions generated'));
await page.locator('#coachDays button').first().click();await page.getByRole('button',{name:'Use this workout in today’s check-in',exact:true}).click();await page.locator('#sleep_hours').fill('08:00');await page.locator('#recommendBtn').click();await page.waitForFunction(()=>document.getElementById('submitStatus').textContent.includes('Decision locked'));
await page.locator('#coachTodayOpen').click();await page.getByRole('button',{name:'Lock pre-run expectation',exact:true}).click();await page.getByRole('button',{name:'Accept adjustment',exact:true}).waitFor();await page.getByRole('button',{name:'Accept adjustment',exact:true}).click();await page.getByText('Pre-run choice: accept',{exact:true}).waitFor();
await page.locator('#ex_distance').fill('5');await page.locator('#ex_duration').fill('32');await page.locator('#ex_hr').fill('138');await page.locator('#ex_rpe').fill('3');await page.getByRole('button',{name:'Save execution and evaluate',exact:true}).click();await page.getByRole('heading',{name:'Expected vs actual',exact:true}).waitFor();await page.screenshot({path:'/tmp/strideai-coach-mobile.png',fullPage:true});
await page.locator('[data-tab="review"]').click();await page.waitForFunction(()=>document.getElementById('coachReview').textContent.includes('completed'));
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);console.log(JSON.stringify({errors,overflow,review:await page.locator('#coachReview').innerText()}));await browser.close();if(errors.length||overflow)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
