"""Progressive profile, living plan, execution proof and weekly review within the existing app."""

PANEL = r"""
<section id="athlete" class="panel">
 <div class="card"><h2>Athlete profile</h2><p class="hint">Start with what you know. Save more later as your training history grows. Targets use fitness evidence, not your race ambition.</p><p id="athleteCoverage" class="compare"></p>
 <form id="athleteForm"><div id="athleteFields" class="grid"></div>
 <div class="field"><label for="athleteDays">Running days</label><div id="athleteDays" class="checks"></div></div>
 <div class="field"><label for="longDay">Long-run day</label><select id="longDay"><option value="">Last available day (default)</option></select></div>
 <div class="checks"><label><input id="addStrength" type="checkbox"> Include strength training</label></div><p class="hint">Strength days are independent of running days. For tennis and strength on Tuesday without a run, leave Tuesday unchecked above and select Tuesday strength below. Session time limits still apply.</p><div id="strengthDays" class="checks" style="flex-wrap:wrap"></div>
 <div class="field"><label for="athletePB">Personal bests: km, time HH:MM:SS, date YYYY-MM-DD (one per line)</label><textarea id="athletePB" placeholder="21.0975, 01:43:08, 2026-02-01"></textarea></div>
 <details><summary>Health history and constraints</summary><div class="field"><label for="athleteHealth">Date, resting HR, HRV ms, sleep hours (blank values allowed)</label><textarea id="athleteHealth" placeholder="2026-09-16, 44, 55, 7.5"></textarea></div>
 <div class="field"><label for="athleteInjury">Injury history</label><textarea id="athleteInjury" maxlength="2000"></textarea></div>
 <div class="checks"><label><input id="athleteActiveInjury" type="checkbox"> Current injury / unresolved pain: pause automatic running</label></div>
 <div class="field"><label for="athleteConstraints">Other constraints (for review; not automatically interpreted)</label><textarea id="athleteConstraints" maxlength="2000"></textarea></div></details>
 <button class="primary">Save profile</button><p id="athleteStatus" role="status"></p></form></div>
 <div class="card"><h2>Your historical runs and races</h2><p class="hint">Existing Strava and imported Garmin activities are included. Connect Strava in Data or import an activity file below.</p>
 <input id="coachImport" type="file" accept=".csv,.tcx"><button id="coachImportBtn" class="secondary">Import Garmin CSV / TCX</button><p id="coachImportStatus" role="status"></p></div>
</section>
<section id="coach" class="panel">
 <div class="card"><h2>Living training plan</h2><p class="hint">Planned → Recommended adjustment → Executed → Evaluated</p><p>Save your race in Plan, then generate a first pass here.</p>
 <div class="grid"><div class="field"><label for="coachStart">Start date</label><input id="coachStart" type="date"></div><div class="checks"><label><input id="coachReplace" type="checkbox"> Replace future, unlocked sessions</label></div></div>
 <button id="coachGenerate" class="primary">Generate race plan</button><p id="coachStatus" role="status"></p>
 <div class="grid"><div class="field"><label for="startMode">Plan start option</label><select id="startMode"><option value="custom">Use start date above</option><option value="today">Today</option><option value="next_monday">Next Monday</option><option value="recommended">Recommended race-specific start</option></select></div><div class="field"><label for="blockWeeks">Block length (weeks; recommended start only)</label><input id="blockWeeks" type="number" min="1" max="32"></div></div><p id="setupNote" class="hint"></p>
 <div><h3>Race-time estimate</h3><p id="raceForecast" class="compare">Add a recent dated race/PB to establish a baseline.</p><p id="raceWeatherSummary" class="hint"></p><details><summary>How this estimate is calculated</summary><div id="raceForecastDetails"></div></details></div>
 <div class="field"><label for="coachWeek">Week beginning</label><select id="coachWeek"></select></div><div id="coachDays"></div></div>
 <div id="coachDetail" class="card" hidden></div>
 <div class="card"><h2>Athlete intelligence</h2><p class="hint">Observations have sample counts and uncertainty. A choice to decline advice is not evidence of a successful workout.</p><div id="coachTraits"></div></div>
</section>
<section id="review" class="panel"><div class="card"><h2>Weekly review</h2><div class="field"><label for="reviewDate">Choose a date in the week</label><input id="reviewDate" type="date"></div><button id="reviewLoad" class="secondary">Review week</button><div id="coachReview" aria-live="polite"></div></div></section>
"""
TODAY = r"""<div class="card"><h2>Your training loop</h2><p id="coachToday">Loading your plan…</p><button id="coachTodayOpen" type="button" class="secondary">Open today’s workout</button><p class="hint">Save your recovery check-in below, then lock expectations before running. After syncing, link the run and compare the result.</p></div>"""
SCRIPT = r"""
<script>
(()=>{
const $=id=>document.getElementById(id);let rows=[],profile={},selected=null,today='',detailStage='all';
const call=async(path,method='GET',body)=>{if(body&&path.endsWith('/profile')){body.long_run_day=$('longDay').value===''?null:Number($('longDay').value);body.include_strength=$('addStrength').checked;body.strength_days=[...document.querySelectorAll('[name=strengthDay]:checked')].map(i=>Number(i.value));}if(body&&path.endsWith('/plan')){body.start_mode=$('startMode').value;body.duration_weeks=$('blockWeeks').value?Number($('blockWeeks').value):null;if(body.start_mode!=='custom')delete body.start_date;}const r=await fetch(path,{method,headers:{'X-StrideAI-Key':localStorage.getItem('strideai_app_key')||'',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'Check your values and try again.');return d};
const el=(host,tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;host.append(n);return n};
const button=(host,label,fn)=>{const b=el(host,'button',label);b.type='button';b.className='secondary';b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){$('coachStatus').textContent=e.message;el(host,'p',e.message).setAttribute('role','alert')}finally{b.disabled=false}};return b};
const pace=v=>v==null?'Unknown':`${Math.floor(Math.round(v)/60)}:${String(Math.round(v)%60).padStart(2,'0')}/km`;
const range=(v,format=x=>String(x))=>v?v.map(format).join(' – '):'Not yet known';
const fields=[['age','Age','number',16,100],['sex','Sex (optional)','select',['','female','male','intersex','prefer_not_to_say']],['gender','Gender (optional)','text'],['height_cm','Height (cm)','number',100,250],['weight_kg','Weight (kg)','number',25,250],['running_years','Running experience (years)','number',0,90],['recent_weekly_km','Recent weekly running (km)','number',0,250],['resting_hr','Resting HR','number',20,220],['hrv_ms','Usual HRV (ms)','number',1,500],['vo2max','VO2max','number',10,100],['threshold_pace','Threshold pace (seconds/km)','number',120,1200],['threshold_hr','Threshold HR','number',60,230],['max_hr','Maximum HR','number',80,240],['max_session_minutes','Maximum session time (minutes)','number',10,240],['race_priority','Race priority','select',['A','B','C']]];
 ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach((label,i)=>{el($('longDay'),'option',label).value=i;const l=el($('strengthDays'),'label',label+' strength ');const input=el(l,'input');input.type='checkbox';input.value=i;input.name='strengthDay';});
 async function refreshSetup(){try{const s=await call('/app/api/coach/plan-setup');if(!$('blockWeeks').value)$('blockWeeks').value=s.recommended_weeks;$('setupNote').textContent=`Suggested ${s.recommended_weeks} weeks, starting ${s.recommended_start}. ${s.note}`;const p=await call('/app/api/coach/race-prediction');const clock=v=>`${Math.floor(v/3600)}:${String(Math.floor(v%3600/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`;$('raceForecast').textContent=p.status==='estimated'?`${clock(p.predicted_seconds)} · planning range ${p.range_seconds.map(clock).join(' – ')} · goal ${clock(p.goal_seconds)}`:p.reason;
$('raceWeatherSummary').textContent=p.weather?.summary||'';
const detail=$('raceForecastDetails');detail.replaceChildren();for(const value of [p.reason,p.training_progress?.reason,p.weather_explanation,p.weather?.method,p.limitations])if(value)el(detail,'p',value);
if(p.weather?.source_url){const a=el(detail,'a','Weather: Open-Meteo');a.href=p.weather.source_url;a.target='_blank';a.rel='noopener';};}catch(e){$('setupNote').textContent=e.message;}}
 document.querySelector('[data-tab="coach"]').addEventListener('click',refreshSetup);
for(const [key,label,type,min,max] of fields){const f=el($('athleteFields'),'div');f.className='field';const l=el(f,'label',label);l.htmlFor='ap_'+key;const input=el(f,type==='select'?'select':'input');input.id='ap_'+key;if(type==='select'){for(const v of min){const o=el(input,'option',v||'Not provided');o.value=v}}else{input.type=type;if(type==='number'){input.min=min;input.max=max;input.step=key==='age'||key==='max_session_minutes'?'1':'any'}}}
['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach((label,i)=>{const l=el($('athleteDays'),'label',label+' ');const input=el(l,'input');input.type='checkbox';input.value=i;input.name='availableDay'});
window.addEventListener('strideai:goal-saved',refreshSetup);
async function loadProfile(){const data=await call('/app/api/coach/profile');profile=data.profile;$('longDay').value=profile.long_run_day??'';$('addStrength').checked=profile.include_strength;document.querySelectorAll('[name=strengthDay]').forEach(i=>i.checked=profile.strength_days.includes(Number(i.value)));today=data.today;for(const [k] of fields)$('ap_'+k).value=profile[k]??'';document.querySelectorAll('[name=availableDay]').forEach(i=>i.checked=profile.available_days.includes(Number(i.value)));$('athleteInjury').value=profile.injury_history;$('athleteConstraints').value=profile.constraints;$('athleteActiveInjury').checked=profile.active_injury;$('athletePB').value=profile.pbs.map(p=>`${p.distance_km}, ${String(Math.floor(p.time_seconds/3600)).padStart(2,'0')}:${String(Math.floor(p.time_seconds%3600/60)).padStart(2,'0')}:${String(Math.round(p.time_seconds%60)).padStart(2,'0')}, ${p.date||''}`).join('\n');$('athleteHealth').value=profile.health_history.map(h=>[h.date,h.resting_hr??'',h.hrv_ms??'',h.sleep_hours??''].join(', ')).join('\n');$('athleteCoverage').textContent=`${data.historical_runs} historical runs available. Optional details can be added anytime.`;if(!$('coachStart').value)$('coachStart').value=today;if(!$('reviewDate').value)$('reviewDate').value=today;window.dispatchEvent(new Event('strideai:profile-loaded'));}
$('athleteForm').onsubmit=async e=>{e.preventDefault();try{const data={};for(const [k,,t] of fields){const v=$('ap_'+k).value;data[k]=v===''?null:t==='number'?Number(v):v}data.available_days=[...document.querySelectorAll('[name=availableDay]:checked')].map(i=>Number(i.value));data.injury_history=$('athleteInjury').value;data.constraints=$('athleteConstraints').value;data.active_injury=$('athleteActiveInjury').checked;data.pbs=$('athletePB').value.trim().split('\n').filter(Boolean).map(line=>{const [km,time,day]=line.split(',').map(x=>x.trim());if(!/^\d{1,3}:[0-5]\d:[0-5]\d$/.test(time))throw new Error('PB time must use HH:MM:SS');const [h,m,s]=time.split(':').map(Number);return {distance_km:Number(km),time_seconds:h*3600+m*60+s,date:day||null}});data.health_history=$('athleteHealth').value.trim().split('\n').filter(Boolean).map(line=>{const [date,rhr,hrv,sleep]=line.split(',').map(x=>x.trim());return {date,resting_hr:rhr?Number(rhr):null,hrv_ms:hrv?Number(hrv):null,sleep_hours:sleep?Number(sleep):null}});await call('/app/api/coach/profile','PATCH',data);$('athleteStatus').textContent='Profile saved. Existing predictions stay unchanged.';await loadProfile();await refreshSetup()}catch(err){$('athleteStatus').textContent=err.message}};
$('coachImportBtn').onclick=async()=>{try{const f=$('coachImport').files[0];if(!f)throw new Error('Choose a CSV or TCX file.');const body=new FormData();body.append('file',f);const r=await fetch(`/v3/activities/import/${f.name.toLowerCase().endsWith('.tcx')?'tcx':'garmin-csv'}?athlete_id=viet`,{method:'POST',headers:{'X-StrideAI-Key':localStorage.getItem('strideai_app_key')||''},body});const d=await r.json();if(!r.ok)throw new Error(d.detail);$('coachImportStatus').textContent=`${d.inserted} new and ${d.updated} updated activities.`;await loadProfile()}catch(e){$('coachImportStatus').textContent=e.message}};
function switchTab(name){document.querySelector(`[data-tab="${name}"]`).click()}
function weekOf(day){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10)}
async function loadWorkouts(){rows=await call('/app/api/coach/workouts');const prev=$('coachWeek').value;$('coachWeek').replaceChildren();for(const week of [...new Set(rows.map(w=>weekOf(w.date)))]){const o=el($('coachWeek'),'option',week);o.value=week}if([...$('coachWeek').options].some(o=>o.value===prev))$('coachWeek').value=prev;else if(today&&[...$('coachWeek').options].some(o=>o.value===weekOf(today)))$('coachWeek').value=weekOf(today);showDays();const w=rows.find(w=>w.date===today);$('coachToday').textContent=w?`${w.current.distance_km} km · ${w.current.purpose} · ${w.state.replaceAll('_',' ')}`:'Use guided setup in You to choose a plan, or check in today.';window.dispatchEvent(new Event('strideai:workouts-loaded'));if(selected){const fresh=rows.find(w=>w.id===selected.id);if(fresh)await detail(fresh)}}
function showDays(){const host=$('coachDays');host.replaceChildren();if(!rows.length){el(host,'p','No living plan yet. Create a plan above, or bring your own through guided setup in You.');return}for(const w of rows.filter(w=>weekOf(w.date)===$('coachWeek').value)){const card=el(host,'div');card.className='history-item';el(card,'strong',`${w.date} · ${w.current.distance_km===0&&w.current.strength_session?"strength · "+w.current.strength_minutes+" min":w.current.kind+" · "+w.current.distance_km+" km"}`);el(card,'p',`${w.original.key_session?'Key session · ':''}${w.state.replaceAll('_',' ')} · original ${w.original.distance_km} km`);button(card,'Open workout',()=>{detailStage='all';detail(w)})}}
function showTargets(host,w){el(host,'p',w.purpose);if(w.distance_km===0&&w.strength_session){el(host,'p',`${w.strength_minutes} minutes strength · no run scheduled`);el(host,'p',w.strength_instructions);el(host,'p',w.instructions);return;}el(host,'p',`${w.distance_km} km · about ${w.duration_minutes} minutes`);el(host,'p',`Pace ${range(w.pace_target,pace)} · HR ${range(w.hr_target)} · RPE ${range(w.rpe_target)}`);el(host,'p',w.instructions);if(w.strength_session)el(host,'p',`Strength: ${w.strength_minutes} minutes. ${w.strength_instructions}`)}
window.strideOpenWorkout=async(w,stage)=>{detailStage=stage;await detail(w)};
async function detail(w){selected=w;const host=$('coachDetail');host.hidden=false;host.replaceChildren();el(host,'h2',`${w.date} · ${w.current.kind}`);if(detailStage!=='review')showTargets(host,w.current);if(w.current.distance_km>0&&detailStage!=='execute'&&detailStage!=='review')el(host,'p','Expected session quality: '+(w.prediction?.recommended_expectation.quality||'Lock a pre-run expectation after your check-in.'));
if(detailStage!=='execute'&&detailStage!=='review'&&w.state==='planned'&&w.date===today&&w.current.distance_km>0){if(detailStage==='all')button(host,'Use this workout in today’s check-in',()=>{switchTab('today');$('checkin_date').value=w.date;$('planned_activity_type').value='run';$('planned_activity_type').dispatchEvent(new Event('change'));$('planned_distance_km').value=w.current.distance_km;$('planned_intensity').value=w.current.kind==='threshold'?'threshold':w.current.kind==='race'?'race':'easy'});button(host,'Lock pre-run expectation',async()=>{await call(`/app/api/coach/workouts/${w.id}/predict`,'POST');await loadWorkouts()})}
if(w.prediction&&detailStage!=='execute'&&detailStage!=='review'){const p=w.prediction;el(host,'h3','What StrideAI expects');showTargets(host,p.recommended);el(host,'p',p.reason);const reasoning=el(host,'details');el(reasoning,'summary','Prediction evidence');el(reasoning,'p',`Prediction basis: ${p.recommended_expectation.basis}; ${p.recommended_expectation.samples} comparable sessions.`);el(reasoning,'p',`AI reasoning: ${p.ai_trace.fallback?'deterministic fallback':p.ai_trace.model}`);for(const warning of p.warnings)el(host,'p',warning);const week=el(host,'details');el(week,'summary','Effect on the rest of this week');for(const e of p.week_effect)el(week,'p',`${e.date}: ${e.before_km} → ${e.after_km} km. ${e.reason}`);if(!w.choice&&!w.execution){button(host,'Accept adjustment',async()=>{await call(`/app/api/coach/workouts/${w.id}/decision`,'POST',{choice:'accept'});await loadWorkouts()});button(host,'Decline adjustment',async()=>{await call(`/app/api/coach/workouts/${w.id}/decision`,'POST',{choice:'decline'});await loadWorkouts()})}else el(host,'p','Pre-run choice: '+(w.choice||'Not recorded'));}
if(w.evaluation){const e=w.evaluation;el(host,'h3','Expected vs actual');el(host,'p',e.explanation);const table=el(host,'table');table.style.width='100%';for(const line of [['Metric','Expected','Actual','Error'],['Pace',pace(e.expected?.pace),pace(e.actual_pace),e.pace_error_seconds_km==null?'Unknown':`${e.pace_error_seconds_km} sec/km`],['HR',e.expected?.hr??'Unknown',w.execution.average_hr??'Unknown',e.hr_error_bpm??'Unknown'],['RPE',e.expected?.rpe??'Unknown',w.execution.rpe??'Unknown',e.rpe_error??'Unknown']]){const tr=el(table,'tr');for(const v of line)el(tr,'td',String(v))}el(host,'p',`Completion ${Math.round(e.completion_ratio*100)}% · HR drift ${e.hr_drift_pct==null?'Unknown':e.hr_drift_pct+'%'} · pace variation ${e.pace_consistency_cv_pct==null?'Unknown':e.pace_consistency_cv_pct+'%'}`);el(host,'h3','What changes next');for(const change of e.next_changes)el(host,'p',`${change.date}: ${change.before_km} → ${change.after_km} km. ${change.reason}`);if(!e.next_changes.length)el(host,'p','Keep the current plan. This outcome adds evidence to athlete intelligence.');for(const v of e.limitations)el(host,'p',v).className='hint';}
else if(w.execution){button(host,'Evaluate executed workout',async()=>{await call(`/app/api/coach/workouts/${w.id}/evaluate`,'POST');await loadWorkouts();await loadTraits();await refreshSetup()})}
else if((detailStage==='all'||detailStage==='execute')&&w.date<=today&&w.original.distance_km>0){el(host,'h3','After the run');el(host,'p','Link a synced activity, or enter the actual totals. RPE is your perceived effort; unknown values stay blank.');const form=el(host,'form');const grid=el(form,'div');grid.className='grid';const input=(name,label,type='number')=>{const f=el(grid,'div');f.className='field';const l=el(f,'label',label);l.htmlFor='ex_'+name;const i=el(f,type==='select'?'select':'input');i.id='ex_'+name;i.name=name;if(type!=='select'){i.type=type;if(type==='number'){i.min=0;i.step='any'}}return i};const activity=input('activity','Synced run','select');el(activity,'option','Manual entry').value='';const acts=await call('/app/api/coach/activities?day='+w.date);for(const a of acts)el(activity,'option',`${a.name||a.source} · ${a.distance_km} km`).value=a.id;input('distance','Actual distance (km)');input('duration','Actual duration (minutes)');input('hr','Average HR');const rpe=input('rpe','RPE 0–10');rpe.max=10;input('completed','Completed intended session','checkbox').checked=true;input('pain','Pain during / after','checkbox');const notes=input('notes','Notes','text');notes.maxLength=2000;const splitDetails=el(form,'details');el(splitDetails,'summary','Add detailed splits (optional)');const splitLabel=el(splitDetails,'label','Optional full-run splits: km, seconds, average HR (one per line)');splitLabel.htmlFor='ex_splits';const split=el(splitDetails,'textarea');split.id='ex_splits';split.name='splits';const submit=el(form,'button','Save execution and evaluate');submit.className='primary';submit.type='submit';form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;try{const n=name=>form.elements[name].value===''?null:Number(form.elements[name].value);const x={activity_id:n('activity'),distance_km:n('distance'),duration_seconds:n('duration')==null?null:n('duration')*60,average_hr:n('hr'),rpe:n('rpe'),completed:form.elements.completed.checked,pain:form.elements.pain.checked,notes:notes.value,splits:split.value.trim().split('\n').filter(Boolean).map(line=>{const [d,t,h]=line.split(',').map(x=>x.trim());return {distance_km:Number(d),duration_seconds:Number(t),average_hr:h?Number(h):null}})};await call(`/app/api/coach/workouts/${w.id}/execution`,'POST',x);await call(`/app/api/coach/workouts/${w.id}/evaluate`,'POST');await loadWorkouts();await loadTraits();await refreshSetup()}catch(e){el(form,'p',e.message).setAttribute('role','alert')}finally{submit.disabled=false}}}
}
async function loadTraits(){const ts=await call('/app/api/coach/intelligence');const host=$('coachTraits');host.replaceChildren();const learned=Object.entries(ts).filter(([,t])=>t.samples>0);if(!learned.length)el(host,'p','Still learning. Patterns will appear as you record more sessions.');for(const [name,t] of learned){const d=el(host,'details');el(d,'summary',`${name.replaceAll('_',' ')} · ${t.samples} observations · ${t.confidence} confidence`);el(d,'p',t.evidence);if(t.value)for(const [k,v] of Object.entries(t.value))el(d,'p',`${k.replaceAll('_',' ')}: ${v??'Unknown'}`)}}
async function review(){const d=await call('/app/api/coach/review?week='+$('reviewDate').value);const host=$('coachReview');host.replaceChildren();el(host,'h3',`Week of ${d.week} · through ${d.through}`);el(host,'p',`${d.completed_km} km completed · ${d.planned_km} km originally planned · ${d.current_plan_km} km current plan`);el(host,'p',`Load (minutes × RPE): ${d.recorded_load_minutes_rpe} recorded / ${d.planned_load_minutes_rpe} planned`);el(host,'p',d.load_coverage);el(host,'h3','Key sessions');for(const s of d.key_sessions)el(host,'p',`${s.date}: ${s.purpose} · ${s.quality}`);el(host,'p',d.fitness_trend);el(host,'p',d.recovery_trend);el(host,'h3','What StrideAI learned');for(const s of d.learned_this_week)el(host,'p',s);el(host,'h3','Next week');for(const s of d.next_week_changes)el(host,'p',`${s.date}: ${s.before_km} → ${s.after_km} km. ${s.reason}`);el(host,'p',d.next_week_reason)}
$('coachWeek').onchange=showDays;$('reviewLoad').onclick=()=>review().catch(e=>$('coachReview').textContent=e.message);
$('coachGenerate').onclick=async()=>{const b=$('coachGenerate');b.disabled=true;try{const d=await call('/app/api/coach/plan','POST',{start_date:$('coachStart').value,replace_existing:$('coachReplace').checked});$('coachStatus').textContent=`${d.workouts} sessions generated. ${d.assumptions.join(' ')} Race feasibility: ${d.race_feasibility}.`;await loadWorkouts()}catch(e){$('coachStatus').textContent=e.message}finally{b.disabled=false}};
$('coachTodayOpen').onclick=async()=>{switchTab('coach');await loadWorkouts();const w=rows.find(w=>w.date===today);if(w)await detail(w)};
for(const tab of ['athlete','coach','review'])document.querySelector(`[data-tab="${tab}"]`).addEventListener('click',()=>{const task=tab==='athlete'?loadProfile():tab==='coach'?Promise.all([loadWorkouts(),loadTraits()]):review();task.catch(e=>$('coachStatus').textContent=e.message)});
window.addEventListener('strideai:strava-synced',()=>loadWorkouts().catch(()=>{}));
window.addEventListener('strideai:checkin-saved',()=>loadWorkouts().catch(()=>{}));
$('saveKey').addEventListener('click',()=>loadProfile().then(loadWorkouts).catch(()=>{}));
loadProfile().then(loadWorkouts).catch(e=>$('coachToday').textContent=e.message);
})();
</script>
"""


def enhance_athlete_ui(html):
    html = html.replace(
        '<button data-tab="plan">Plan</button>',
        '<button data-tab="plan">Plan</button><button data-tab="athlete">Athlete</button><button data-tab="coach">Coach</button><button data-tab="review">Review</button>',
        1,
    )
    html = html.replace('<section id="history"', PANEL + '<section id="history"', 1)
    html = html.replace(
        '<section id="today" class="panel active">',
        '<section id="today" class="panel active">' + TODAY,
        1,
    )
    html = html.replace(
        "</head>",
        "<style>.nav{display:flex!important;flex-wrap:wrap}.nav button{flex:1 0 70px}#coachDetail table td{padding:8px;border-bottom:1px solid #e5e7eb}#coachDetail button{margin:6px 6px 6px 0}#coachTraits details{padding:10px 0}#athleteHealth,#athletePB{min-height:90px}</style></head>",
        1,
    )
    html = html.replace(
        "$('submitStatus').textContent='Decision locked and recommendation saved.';",
        "$('submitStatus').textContent='Decision locked and recommendation saved. Open today’s workout to lock execution targets.';window.dispatchEvent(new Event('strideai:checkin-saved'));",
        1,
    )
    return html.replace("</body>", SCRIPT + "</body>", 1)
